package pbol_project;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Scanner;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author G.Kristha Program by : Gerardus Kristha_215314004
 */
public class Aplikasi_Kasir extends javax.swing.JFrame {

    private Barang tempBarang, barangMasuk;
    double hargaTransTotal = 0;
    private int nomorNota = 1;
    private Nota notaBarang;

    /**
     * Creates new form Aplikasi_Kasir
     */
    public Aplikasi_Kasir() throws Exception {
        initComponents();
        this.tanggalNota();
        notaBarang = new Nota();
        this.generatedNoNota();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNoNota = new javax.swing.JLabel();
        labelJudul1 = new javax.swing.JLabel();
        tfCariBarang = new javax.swing.JTextField();
        tfNoNota = new javax.swing.JTextField();
        labelCariBarang = new javax.swing.JLabel();
        labelTanggal = new javax.swing.JLabel();
        tfTanggal = new javax.swing.JTextField();
        labelQty = new javax.swing.JLabel();
        tfQty = new javax.swing.JTextField();
        buttonInputBarang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        labelTotal = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        tfBayar = new javax.swing.JTextField();
        labelBayar = new javax.swing.JLabel();
        labelKembali = new javax.swing.JLabel();
        tfKembali = new javax.swing.JTextField();
        buttonSelesai = new javax.swing.JButton();
        buttonBatal = new javax.swing.JButton();
        labelHarga = new javax.swing.JLabel();
        tfHarga = new javax.swing.JTextField();
        buttonCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1000, 500));
        setMinimumSize(new java.awt.Dimension(1000, 535));
        setPreferredSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        labelNoNota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNoNota.setForeground(new java.awt.Color(255, 255, 255));
        labelNoNota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNoNota.setText("No.Nota        :");

        labelJudul1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelJudul1.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJudul1.setText("APLIKASI KASIR");

        tfNoNota.setEditable(false);

        labelCariBarang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCariBarang.setForeground(new java.awt.Color(255, 255, 255));
        labelCariBarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCariBarang.setText("Cari Barang   :");

        labelTanggal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTanggal.setForeground(new java.awt.Color(255, 255, 255));
        labelTanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTanggal.setText("Tanggal  :");

        tfTanggal.setEditable(false);

        labelQty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelQty.setForeground(new java.awt.Color(255, 255, 255));
        labelQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelQty.setText("Qty  :");

        buttonInputBarang.setBackground(new java.awt.Color(255, 153, 51));
        buttonInputBarang.setForeground(new java.awt.Color(255, 255, 255));
        buttonInputBarang.setText("INPUT BARANG");
        buttonInputBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInputBarangActionPerformed(evt);
            }
        });

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Barang", "Harga Barang", "Qty", "Total Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelTransaksi);
        if (tabelTransaksi.getColumnModel().getColumnCount() > 0) {
            tabelTransaksi.getColumnModel().getColumn(0).setPreferredWidth(300);
            tabelTransaksi.getColumnModel().getColumn(2).setPreferredWidth(50);
            tabelTransaksi.getColumnModel().getColumn(3).setPreferredWidth(120);
        }

        labelTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotal.setForeground(new java.awt.Color(255, 255, 255));
        labelTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotal.setText("TOTAL        : Rp");

        tfTotal.setEditable(false);

        tfBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBayarActionPerformed(evt);
            }
        });

        labelBayar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelBayar.setForeground(new java.awt.Color(255, 255, 255));
        labelBayar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelBayar.setText("BAYAR           :  Rp.");

        labelKembali.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelKembali.setForeground(new java.awt.Color(255, 255, 255));
        labelKembali.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelKembali.setText("KEMBALI        :  Rp.");

        tfKembali.setEditable(false);

        buttonSelesai.setBackground(new java.awt.Color(0, 255, 153));
        buttonSelesai.setForeground(new java.awt.Color(0, 102, 102));
        buttonSelesai.setText("SELESAI");
        buttonSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelesaiActionPerformed(evt);
            }
        });

        buttonBatal.setBackground(new java.awt.Color(255, 51, 51));
        buttonBatal.setForeground(new java.awt.Color(255, 255, 255));
        buttonBatal.setText("BATAL");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        labelHarga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelHarga.setForeground(new java.awt.Color(255, 255, 255));
        labelHarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHarga.setText("Harga            :");

        tfHarga.setEditable(false);

        buttonCari.setBackground(new java.awt.Color(255, 153, 51));
        buttonCari.setForeground(new java.awt.Color(255, 255, 255));
        buttonCari.setText("CARI");
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelKembali)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfKembali))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(74, 74, 74)
                                .addComponent(buttonSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelHarga)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfHarga))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelNoNota)
                                            .addComponent(labelCariBarang))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNoNota, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonCari, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTanggal)
                                    .addComponent(labelQty, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfQty, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTanggal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonInputBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(52, 52, 52))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(labelJudul1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(labelJudul1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNoNota)
                    .addComponent(tfNoNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTanggal)
                    .addComponent(tfTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCari))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHarga)
                            .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCariBarang)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelQty)
                                .addComponent(tfQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonInputBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotal)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelBayar)
                            .addComponent(tfBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelKembali)
                            .addComponent(tfKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonInputBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInputBarangActionPerformed
        try {
            double harga = Double.parseDouble(tfHarga.getText());
            double qty = Double.parseDouble(tfQty.getText());
            inputBarang(tempBarang, qty);
            double hargatrans = barangMasuk.getTotalHarga();
            //memasukan ke table
            DefaultTableModel tabel = (DefaultTableModel) tabelTransaksi.getModel();
            if (tfCariBarang.getText().trim().isEmpty()) {
            } else {
                Vector data = new Vector();
                data.add(tempBarang.getNamaBarang());
                data.add(tfHarga.getText());
                data.add(tfQty.getText());
                data.add((int)hargatrans);
                tabel.addRow(data);
            }
            inputNota(barangMasuk);
            tfHarga.setText("");
            tfQty.setText("");
            tfCariBarang.setText("");
            hargaTransTotal += hargatrans;
            tfTotal.setText("" + (int) hargaTransTotal);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Masukan Data Barang secara detail");
        }
    }//GEN-LAST:event_buttonInputBarangActionPerformed

    private void buttonSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelesaiActionPerformed
        try {
            if(tfBayar.getText().isBlank()){
                throw new Exception();
            }else{
            //hapus all isi tabel
            DefaultTableModel model = (DefaultTableModel) tabelTransaksi.getModel();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            //buat nota
            this.generatedNoNota();
            Database rwyTransaksi = new Database();
            rwyTransaksi.riwayatTransaksi(tfNoNota.getText(), (Timestamp.valueOf(tfTanggal.getText())), Integer.valueOf(tfTotal.getText()));
            notaBarang.cetakNota(tfTanggal.getText(), tfNoNota.getText(), barangMasuk);
            this.tambahNoNota();
            this.generatedNoNota();
            JOptionPane.showMessageDialog(null, "Transaksi Selesai");
            notaBarang.hapusDataBarang();
            tfTotal.setText("");
            tfBayar.setText("");
            tfKembali.setText("");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Kesalahan Sistem", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_buttonSelesaiActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        //hapus isi tabel
        DefaultTableModel model = (DefaultTableModel) tabelTransaksi.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        //hapus textfield dalam tampilan
        tfTotal.setText("");
        tfBayar.setText("");
        tfKembali.setText("");
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
        try {
            //connect Database
            Database data = new Database();
            //Cari Barang
            Barang cari = new Barang();
            cari.setIdBarang(tfCariBarang.getText());
            Barang hasil = data.cariData(cari);
            tfHarga.setText(String.valueOf((int) hasil.getHarga()));
            //simpan barnag sementara
            temporaryBarang(hasil);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_buttonCariActionPerformed

    private void tfBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBayarActionPerformed
        double bayar = Double.parseDouble(tfBayar.getText());
        double total = Double.parseDouble(tfTotal.getText());
        double kembali = 0;
        if (tfBayar != null) {
            try {
                kembali = bayar - total;
                if (kembali < 0) {
                    throw new Exception("Input Jumlah Bayar Kembali");
                }
                tfKembali.setText(String.valueOf((int)kembali));
            } catch (Exception e) {
                tfKembali.setText("");
                JOptionPane.showMessageDialog(null,
                        "Kesalahan Input",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_tfBayarActionPerformed

    private void temporaryBarang(Barang temp) {
        tempBarang = new Barang();
        tempBarang.setIdBarang(temp.getIdBarang());
        tempBarang.setNamaBarang(temp.getNamaBarang());
        tempBarang.setHarga((int) temp.getHarga());
    }

    private void inputBarang(Barang barangtemp, double qtyBarang) {
        barangMasuk = new Barang();
        barangMasuk.setIdBarang(barangtemp.getNamaBarang());
        barangMasuk.setNamaBarang(barangtemp.getNamaBarang());
        barangMasuk.setHarga(barangtemp.getHarga());
        barangMasuk.setQty((int) qtyBarang);
    }

    private void inputNota(Barang barangNota) {
        notaBarang.inptDataBarang(barangNota);
    }

    private void tanggalNota() {
        Calendar calendar = Calendar.getInstance();
        Timestamp now = new Timestamp(calendar.getTime().getTime());
        tfTanggal.setText(now.toString());
    }

    private void tambahNoNota() {
        try {
            Scanner bacaNota = new Scanner(new File("No Nota.txt"));
            int tempNoNota = bacaNota.nextInt();
            FileWriter writer = new FileWriter("No Nota.txt");
            writer.write(String.valueOf(tempNoNota + 1));
            writer.close();
        } catch (IOException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Sistem Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void generatedNoNota() {
        try {
            Scanner bacaNota = new Scanner(new File("No Nota.txt"));

            int tempNoNota = bacaNota.nextInt();
            tfNoNota.setText("NOTA00" + String.valueOf(tempNoNota));
        } catch (FileNotFoundException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Kesalahan Sistem", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Aplikasi_Kasir().setVisible(true);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonCari;
    private javax.swing.JButton buttonInputBarang;
    private javax.swing.JButton buttonSelesai;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBayar;
    private javax.swing.JLabel labelCariBarang;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JLabel labelJudul1;
    private javax.swing.JLabel labelKembali;
    private javax.swing.JLabel labelNoNota;
    private javax.swing.JLabel labelQty;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JTextField tfBayar;
    private javax.swing.JTextField tfCariBarang;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfKembali;
    private javax.swing.JTextField tfNoNota;
    private javax.swing.JTextField tfQty;
    private javax.swing.JTextField tfTanggal;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
}
